### ISSUE TITLE
Organization of new algorithm types

### ISSUE THREAD

**Issue by tbsexton** [sknetwork-team/scikit-network#384]
Just finding this library, and *wow*! I wish I had found this sooner. 

Was working on some implementations for edge filtering (see [here](https://arxiv.org/pdf/1701.07336.pdf)) but eventually would love to contribute using this framework.

- Where would such algorithms go w.r.t. the others? A new submodule? 
- Any style guidelines to getting started? I'll admit I am much more familiar with networkx and functional style libraries like jax, pytorch, and autograd (had to write a lot of boilerplate to keep track of node properties in those for my [research](https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=928903)). Have never seen/used scipy's `LinearOperator` so extensively, so any resources on using those? 
- Also interested in vector similarities over graphs, see [here](http://www.michelecoscia.com/wp-content/uploads/2020/03/FULL-CosciaM1099.pdf) and [here](https://www.sciencedirect.com/science/article/pii/S1063520306000546). I see you guys have a lot of diffusion code already, but is simply using e.g. `scipy.linalg.pinv` wrapped in an `Algorithm` ok here?

**Comment by QLutz** [comment]
Hello,

Thank you for your interest in our package!

To answer your questions:

 * Such algorithms would indeed call for a new submodule, whose name can be chosen upon your pull request. What outputs do you think those algorithms should offer?

 * The guidelines for contributing can be found in the [Wiki](https://github.com/sknetwork-team/scikit-network/wiki/Contributing-guide). For SciPy's `LinearOperator`, we relied on the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html).

 * We do not use `scipy.linalg.pinv` as we found it was too costly. However, if you are interested in implementing any papers in particular, please do tell us so we, in turn, can tell you if we think it would make a nice addition to the package.

Looking forward to your answer!

**Comment by tbsexton** [comment]
Definitely the papers I've linked! Actually, the author has implementations in pandas+nx to start from, though they are essentially single scripts. 

see: 
- [Network backboning](http://www.michelecoscia.com/?page_id=287)
- [Node vector distance]()http://www.michelecoscia.com/?page_id=1733)

Both of those would make excellent submodules, IMO. While I am familiar with the algorithms and can use those scripts as a launching point, it would honestly be a little while until I adequately understand your framework to meaningfully contribute. If you decide to add them first, however, I could certainly contribute tests, or add remaining algorithms once I have one or two to follow from.

**Comment by nathandelara** [comment]
Hi,
We took a closer look at the algorithms you proposed.

* If you want to get your hands on the package, the easiest algorithm to implement is probably [Diffusion maps](https://www.sciencedirect.com/science/article/pii/S1063520306000546). This would go directly into `sknetwork.embedding` so you can rely on examples such as `sknetwork.embedding.Spectral`. Most of the necessary primitives seem to be already available in `sknetwork.linalg`.
Do not hesitate to open a dedicated issue or directly a PR so that we can help you!

* [Network Distances](http://www.michelecoscia.com/wp-content/uploads/2020/03/FULL-CosciaM1099.pdf) could go into `sknetwork.ranking`. I would need to have a closer look at the algorithm though to check whether you need Cython or not for this one.

* [Edge filtering](http://www.michelecoscia.com/?page_id=287) would require to implement a new submodule from scratch, something like `sknetwork.edge_filtering`. So, this is slightly more challenging. Maybe we could wait until you are more familiar with the package (and we are more familiar with the algorithm...) for this one. Still, it is an interesting project!

Thanks !
