### ISSUE TITLE
64-bit Louvain? Support more than 2147483647 edges

### ISSUE THREAD

**Issue by fjsj** [sknetwork-team/scikit-network#450]
* scikit-network version: 0.19.1
* Python version: 3.8.5
* Operating System: CentOS Linux 7 (Core)

### Description

Thanks for this great library! I'm trying to run `clustering.Louvain` on graphs with billions of edges (1 to 15 billion) and few millions of nodes (~5 million). The algorithm runs fine with 1,5 billion rows, but with more than that it fails without a traceback and exit code SIGSEV. Since max int is 2147483647, I believe the problem is `louvain.py` uses `np.int32` in multiple places and `louvain_core.pyx` uses `int`s instead of `long`s.

My question is: is it fine to open a PR increasing Louvain to deal with 64-bit integers? Or even leveraging from "fused types" and support both versions (see: https://stackoverflow.com/questions/28112599/writing-cython-for-both-32-bit-and-64-bit)?

**Comment by QLutz** [comment]
Thank you very much for raising this issue.

We made the choice of using `np.int32` because we thought it unlikely that one would surpass that limit. We are glad to see we were wrong. If you are willing to do these changes and test them on your (seemingly beefy) computer, please do open a PR as we won't be able to test it ourselves on the machines at our disposal.

I am unsure as to whether using fused types as described in the post you reference is desirable as it would also affect the memory performance on 64-bit platforms with low RAM. As RAM is, in our experience, the bottleneck for running sknetwork, we'd like to ensure that using `np.int32` is still possible on 64-bit platforms. Do you know of a way to make the type switch depending on the RAM size rather than the OS?

Anyway, we definitely would like to allow for bigger graphs to be loaded, so you can start by implementing these changes if you are willing. By the time those changes are made, we will try to determine wether there is a simple way to implement it in the wheels. At the very least, we will try to offer a convenient way to apply those changes when building the package from sources.

Out of curiosity, what is the configuration of the computer you are using (the RAM amount in particular)?

Thank you for your interest in our package!

**Comment by fjsj** [comment]
Thanks for the quick reply!

> Do you know of a way to make the type switch depending on the RAM size rather than the OS?
Seems it's possible by using fused types and deciding the dtype at the Python-side. What RAM size would be the threshold?

> Out of curiosity, what is the configuration of the computer you are using (the RAM amount in particular)?
Using a cloud provider instance with ~500 GiB of RAM.

**Comment by QLutz** [comment]
*Seems it's possible by using fused types and deciding the dtype at the Python-side. What RAM size would be the threshold?*

Sounds great then. We couldn't touch graphs big enough at 128 GB so I guess 256 would be the threshold.

*Using a cloud provider instance with ~500 GiB of RAM.*

Makes sense.

We are looking forward to your PR then!

**Comment by fjsj** [comment]
Draft PR available: https://github.com/sknetwork-team/scikit-network/pull/456
