### ISSUE TITLE
Building as pure-python for debugging 

### ISSUE THREAD

**Issue by scottagt** [sknetwork-team/scikit-network#473]
Hi, I read in that there is a means to build a "pure python" version of the library on one of the prior issues where individuals were talking about issues debugging in Cython with PyCharm. I too am having trouble debugging in PyCharm due to a similar "NoneType is not callable" exception. I saw in the setup.py that there was an environmental flag to turn off Cythonizing.

I'm wondering what the easiest way to compile a non-Cython version that I can debug with PyCharm on macOS would be? Appreciate any thoughts on this subject.

**Comment by QLutz** [comment]
Hi Scott,

Thanks for raising this issue.

Unfortunately, there is no way to bypass Cython altogether to install the project. Doing so on macOS requires to follow a few extra steps to enable parallelisation properly (see [the Wiki](https://github.com/sknetwork-team/scikit-network/wiki/Cython-specifics#generating-c-code-with-cython-and-compiling-it)) but is otherwise fairly straight forward.

However, once you have compiled the sources, no further compilation is needed as long as you do not create new Cython (i.e. `.pyx`) files.

If you wanted to use the compiled features of the package without any compilation on your end, you could make imports from a pip-installed version of course but it defeats the purpose of your question.

**Comment by scottagt** [comment]
Hi @QLutz, thanks for these details. I'm wanting to bypass Cython so that I can easily debug and inspect the outputs of various algorithms. With pyx files, it is not possible to debug these within PyCharm from my understanding. Right now, I cannot debug except perhaps through using Jupyter notebooks. I think I can "run" scikit-network cells and then "debug" cells with the resulting variables however this is a workaround. 

Could I ask, would it take a lot of work for anyone to convert the Cython segments to pure python? I'm not suggesting anybody on the scikit-network team do this of course but just interested to understand the complexity. :)

Best,
-Scott

**Comment by QLutz** [comment]
It is very much possible to debug from PyCharm even with Cython but it requires to complete the steps given in the Wiki: you must be able to compile the project first (by running `python setup.py build_ext --inplace` at the root of the project), then, all the modules should be available.

Turning the Cython segments into Python would most likely prove cumbersome as many algorithms rely on `.pyx` files at their core (Louvain, PageRank, ...). To the best of my knowledge, Cython lacks a feature that makes it possible to run `.pyx` files directly with the interpreter.

If that's any help, you could revert to the [last release without Cython](https://github.com/sknetwork-team/scikit-network/releases/tag/v0.12.1), but the API and the available features have changed considerably since so it really depends on what you need.

Best,

**Comment by scottagt** [comment]
Oh, that's interesting. I did try doing `python setup.py build_ext --inplace` and then I installed it doing `install` and PyCharm does its module update thing but then still the same errors. It seems that even with doing the "build_ext --inplace" its still creating the .so files? Is that right? And whenever it goes into one of those PyCharm throws the exception. If there is any screenshots I can provide, please let me know. I'm attaching a screenshot of running the `build_ext --inplace` command and the results of attempting to debug with PyCharm after installing the results of the build command.

![pycharm_error](https://user-images.githubusercontent.com/25912784/109673075-a703c700-7b43-11eb-8cf6-c317a114a220.png)
![cythonizing](https://user-images.githubusercontent.com/25912784/109673083-a8cd8a80-7b43-11eb-9c3a-5b6af1e2af3d.png)

**Comment by scottagt** [comment]
I'm attempting to use the BiPropagation Clustering algorithm. I'll take a look at the prior non-Cython release, appreciate the tip to check that out. 👍

**Comment by QLutz** [comment]
Hi Scott,

Sorry, I misunderstood what you were trying to do. Indeed, PyCharm does not make it possible to use the debugger on Cython code (and it seems they do not plan to implement this anytime soon, cf. [here](https://youtrack.jetbrains.com/issue/PY-9476?_ga=2.55164524.61510552.1614758146-421215921.1614758146)).

If that's any help, I've updated the [Wiki](https://github.com/sknetwork-team/scikit-network/wiki/Cython-specifics) to describe a few tips we use when writing Cython code.
