### ISSUE TITLE
SVG graph labels positions

### ISSUE THREAD

**Issue by gsgoncalves** [sknetwork-team/scikit-network#485]
* scikit-network version: 0.23.1
* Python version: 3.8.0
* Operating System: Ubuntu 20.04.2 LTS

For SVG graph
Is it possible to set a positions array for labels, or automatically place them below the nodes?
https://scikit-network.readthedocs.io/en/latest/reference/visualization.html#sknetwork.visualization.graphs.svg_graph

**Comment by nuxion** [comment]
TL;DR graph embedding is about graph topology

I'm new with graph theory, but I believe your problem for label positions is related to graph embeddings. 

Look at this example: [louvain_embedding](https://scikit-network.readthedocs.io/en/latest/tutorials/embedding/louvain_embedding.html)

If you want more information, you can read [this article](https://towardsdatascience.com/graph-embeddings-the-summary-cc6075aba007)

So you should apply some embedding process in order to get the labels positions for `svg_graph`

**Comment by tbonald** [comment]
Thanks for the suggestion.  The position of labels (left, right, above, below) is now available on the dev branch and will be part of the next release (coming soon :-).
